services:
  db:
    image: postgres:16
    container_name: DotnetBackendDemo-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: DotnetBackendDemo
    ports:
      - "5432:5432"
    volumes:
      - DotnetBackendDemo_pgdata:/var/lib/postgresql/data

volumes:
  DotnetBackendDemo_pgdata:
